# https://github.com/NuGet/Home/issues/12227#issuecomment-1550015372
FROM --platform=linux/amd64 mcr.microsoft.com/dotnet/sdk:8.0-preview AS build-env
WORKDIR /App

# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore
# Build and publish a release
RUN dotnet publish --runtime alpine-arm64 -c Release --self-contained true -o out /p:PublishSingleFile=true /p:PublishTrimmed=true

# Build runtime image
FROM alpine:latest

RUN apk add --no-cache libstdc++

WORKDIR /App
COPY --from=build-env /App/out .
ENTRYPOINT ["./Test"]