FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /App

# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore
# Build and publish a release
RUN dotnet publish --runtime alpine-x64 -c Release --self-contained true -o out /p:PublishSingleFile=true /p:PublishTrimmed=true

# Build runtime image
FROM alpine:latest

RUN apk add --no-cache libstdc++

WORKDIR /App
COPY --from=build-env /App/out .
ENTRYPOINT ["./Test"]